

/*
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBD7HkMm0X49tvuc8SLfWw4jJCTagD8NcM',
    appId: '1:224264122028:web:33e1bc10b4b2580d18b909',
    messagingSenderId: '224264122028',
    projectId: 'image-broker',
    authDomain: 'image-broker.firebaseapp.com',
    storageBucket: 'image-broker.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbcRfA3wu6ax1KkR3Q3Oxv0qNAvzlquX8',
    appId: '1:224264122028:android:e5feaf621f06201a18b909',
    messagingSenderId: '224264122028',
    projectId: 'image-broker',
    storageBucket: 'image-broker.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLl2-EcD7Cd_ZvRsxHM1j41OaeTUyDcos',
    appId: '1:224264122028:ios:8f27b7e87fade96518b909',
    messagingSenderId: '224264122028',
    projectId: 'image-broker',
    storageBucket: 'image-broker.appspot.com',
    iosBundleId: 'me.andreealavric.imageBroker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLl2-EcD7Cd_ZvRsxHM1j41OaeTUyDcos',
    appId: '1:224264122028:ios:8f27b7e87fade96518b909',
    messagingSenderId: '224264122028',
    projectId: 'image-broker',
    storageBucket: 'image-broker.appspot.com',
    iosBundleId: 'me.andreealavric.imageBroker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBD7HkMm0X49tvuc8SLfWw4jJCTagD8NcM',
    appId: '1:224264122028:web:69d121eca39049fb18b909',
    messagingSenderId: '224264122028',
    projectId: 'image-broker',
    authDomain: 'image-broker.firebaseapp.com',
    storageBucket: 'image-broker.appspot.com',
  );
}

 */
